# Generated by Django 3.2.18 on 2023-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='memo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
