# Generated by Django 3.2.18 on 2023-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
